apiVersion: v1
kind: Secret
metadata:
  name: analyst-server-secret
type: Opaque
data:
  # ===== MySQL Password =====
  # MYSQL_PASSWORD: hiiiiky
  MYSQL_PASSWORD: aGlpaWlreQ==

  # ===== GMS API Key =====
  # GMS_API_KEY: S13P32A209-a42d3608-1ce2-4906-bd24-8017020ab4c5
  GMS_API_KEY: UzEzUDMyQTIwOS1hNDJkMzYwOC0xY2UyLTQ5MDYtYmQyNC04MDE3MDIwYWI0YzU=