apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - middleware.yaml
  - ingress-route.yaml

namespace: dev

images:
- name: kkaebu/user-server
  newTag: dev-b9c249fb
