apiVersion: v1
kind: Secret
metadata:
  name: user-server-secret
type: Opaque
data:
  # DB_USERNAME: tickget
  DB_USERNAME: dGlja2dldA==
  # DB_PASSWORD: hiiiiky
  DB_PASSWORD: aGlpaWlreQ==
  # MINIO_ACCESS_KEY: tickget209
  MINIO_ACCESS_KEY: dGlja2dldDIwOQ==
  # MINIO_SECRET_KEY: hiiiiky209
  MINIO_SECRET_KEY: aGlpaWlreTIwOQ==
