apiVersion: v1
kind: Secret
metadata:
  name: user-server-secret
type: Opaque
data:
  # DB_USERNAME: S13P31A209
  DB_USERNAME: UzEzUDMxQTIwOQ==
  # DB_PASSWORD: tickget209
  DB_PASSWORD: dGlja2dldDIwOQ==
  # MINIO_ACCESS_KEY: miniorootadmin
  MINIO_ACCESS_KEY: bWluaW9yb290YWRtaW4=
  # MINIO_SECRET_KEY: miniorootadmin
  MINIO_SECRET_KEY: bWluaW9yb290YWRtaW4=
