# apps/ticketing-server/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 사용할 base
resources:
- ../../base
# 2. 이 환경(prod)에만 추가할 리소스
- configmap.yaml
- secret.yaml
- middleware.yaml

# 3. 이 환경의 모든 리소스에 'prod' 네임스페이스 적용
namespace: prod

# 4. base의 deployment.yaml 이미지 태그 덮어쓰기
images:
- name: kkaebu/ticketing-server
  newTag: latest # CI가 이 부분을 덮어쓸 예정

# 5. base의 deployment.yaml replicas 덮어쓰기 (예: 운영은 3개)
patches:
- path: patch-replicas.yaml
  target:
    kind: Deployment
    name: ticketing-server-deployment