apiVersion: v1
kind: Secret
metadata:
  name: seatmap-server-secret
type: Opaque
data:
  # .env 파일의 보안 데이터를 Base64 인코딩
  
  # MINIO_ACCESS_KEY: tickget209
  MINIO_ACCESS_KEY: dGlja2dldDIwOQ==

  # MINIO_SECRET_KEY: hiiiiky209
  MINIO_SECRET_KEY: aGlpaWlreTIwOQ==
  
  # TICKGET_API_TOKEN: eyJhbGciOiJIUzUx...
  TICKGET_API_TOKEN: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lJNUlpd2lZWFYwYVdWeVlpSTZJall5TmpBeU5qTXlPbHRhRFhrZ1RIazVlSHB2Y21WdVpHRjBaVU55YjNWMFpYTWlMQ0p0YjJOMWJXVnpaU0k2SUNrZ01TSjkuUlBMTXNPREJpMDB3UGtsdW9JWE1DQ1R3cm9fbGNNN0FuX3prQ0stVmVyX2x1QWItdEFGZloyajJGTlAxUUYtcWJwWGdhWl9ZSmNtSWxSelNkS21tRXc=