apiVersion: v1
kind: Service
metadata:
  name: ticketing-server-service
spec:
  # ClusterIP: 클러스터 내부에서만 접근 가능
  # (외부 노출은 추후 Ingress로 설정)
  type: ClusterIP 
  selector:
    app: ticketing-server # 02-deployment.yaml의 label과 일치해야 함
  ports:
  - protocol: TCP
    port: 80 # 서비스가 노출할 포트
    targetPort: 8080 # 파드의 컨테이너 포트