apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analyst-server-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Tickget/tickget-k8s-manifest.git # 본인의 Git Repo URL
    targetRevision: dev
    path: apps/analyst-server/overlays/dev # Kustomize overlay 경로

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
