apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticketing-server-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Tickget/tickget-k8s-manifest.git
    targetRevision: dev
    path: apps/ticketing-server/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  # HPA가 관리하는 replicas 필드는 ArgoCD 동기화에서 제외
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: ticketing-server-deployment
    jsonPointers:
    - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
