apiVersion: v1
kind: Service
metadata:
  name: captcha-server-service
spec:
  selector:
    app: captcha-server
  ports:
    - protocol: TCP
      port: 80        # 서비스가 노출하는 포트
      targetPort: 8080  # 파드의 컨테이너 포트
  type: ClusterIP  # 클러스터 내부에서만 접근 가능 (Ingress를 통해 외부 노출)
