apiVersion: v1
kind: Secret
metadata:
  name: bot-server-secret
type: Opaque
data:
  # MinIO 인증 정보 (Base64 인코딩)
  # minioadmin -> bWluaW9hZG1pbg==
  # miniorootadmin -> bWluaW9yb290YWRtaW4=
  MINIO_ACCESS_KEY: bWluaW9yb290YWRtaW4=
  MINIO_SECRET_KEY: bWluaW9yb290YWRtaW4=
