apiVersion: v1
kind: ConfigMap
metadata:
  name: search-server-config
data:
  # Elasticsearch 연결 정보 (db 네임스페이스)
  ELASTICSEARCH_HOSTS: "http://elasticsearch-service.db.svc.cluster.local:9200"

  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_SEARCH: "DEBUG"
