apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - middleware.yaml
  - ingress-route.yaml

namespace: dev

images:
- name: kkaebu/search-server
  newTag: dev-65ab0f6a
