apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
  - middleware.yaml
  - ingress-route.yaml

namespace: dev

images:
- name: kkaebu/auth-server
  newTag: dev-5004e446

patches:
  - path: patch-hpa.yaml
