apiVersion: v1
kind: Secret
metadata:
  name: auth-server-secret
type: Opaque
data:
  # MySQL Credentials
  # SPRING_DATASOURCE_USERNAME: S13P31A209
  SPRING_DATASOURCE_USERNAME: UzEzUDMxQTIwOQ==
  # SPRING_DATASOURCE_PASSWORD: tickget209
  SPRING_DATASOURCE_PASSWORD: dGlja2dldDIwOQ==

  # Google OAuth2 Credentials
  # GOOGLE_CLIENT_ID: 301819153009-nesq7ufapf1mmq299u26ubmrv3mejotc.apps.googleusercontent.com
  GOOGLE_CLIENT_ID: MzAxODE5MTUzMDA5LW5lc3E3dWZhcGYxbW1xMjk5dTI2dWJtcnYzbWVqb3RjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  # GOOGLE_CLIENT_SECRET: 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
  GOOGLE_CLIENT_SECRET: R09DU1BYLUlvaVcxcldYaC1vbV9zUFRlNHlGNmVpWWpDb2Q=

  # JWT Secret Key
  # JWT_SECRET: tickget-secure-jwt-authentication-key-2024-production-v1-arm64-kubernetes-cluster
  JWT_SECRET: dGlja2dldC1zZWN1cmUtand0LWF1dGhlbnRpY2F0aW9uLWtleS0yMDI0LXByb2R1Y3Rpb24tdjEtYXJtNjQta3ViZXJuZXRlcy1jbHVzdGVy

  # MinIO S3 Credentials
  # MINIO_ACCESS_KEY: miniorootadmin
  MINIO_ACCESS_KEY: bWluaW9yb290YWRtaW4=
  # MINIO_SECRET_KEY: miniorootadmin
  MINIO_SECRET_KEY: bWluaW9yb290YWRtaW4=
