# apps/ticketing-server/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 사용할 base
resources:
- ../../base
# 2. 이 환경(dev)에만 추가할 리소스
- configmap.yaml
- secret.yaml
- middleware.yaml
- ingress-route.yaml

# 3. 이 환경의 모든 리소스에 'dev' 네임스페이스 적용
namespace: dev

# 4. base의 deployment.yaml 이미지 태그 덮어쓰기
images:
- name: kkaebu/ticketing-server
  newTag: dev-870aa4ea

# 5. base의 deployment.yaml replicas 덮어쓰기 (예: dev는 2개만)
patches:
- path: patch-replicas.yaml
  target:
    kind: Deployment
    name: ticketing-server-deployment