apiVersion: v1
kind: Secret
metadata:
  name: ticketing-server-secret
type: Opaque
data:
  # MySQL Credentials
  # DB_USERNAME: S13P31A209
  DB_USERNAME: UzEzUDMxQTIwOQ==
  # DB_PASSWORD: tickget209
  DB_PASSWORD: dGlja2dldDIwOQ==

  # MongoDB credentials are embedded in URI in ConfigMap
  # No separate secret needed for MongoDB
