apiVersion: v1
kind: ConfigMap
metadata:
  name: test-server-config
  namespace: default
data:
  # MySQL URL (비밀번호 제외)
  SPRING_DATASOURCE_URL: "jdbc:mysql://ssafy-mysql-db.mysql.database.azure.com:3306/S13P31A209?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8"
  
  # Redis (K8s 내부 서비스 이름)
  SPRING_DATA_REDIS_HOST: "redis-service" #
  SPRING_DATA_REDIS_PORT: "6379"