apiVersion: v1
kind: Secret
metadata:
  name: room-server-secret
type: Opaque
data:
  # SPRING_DATASOURCE_USERNAME: S13P31A209
  SPRING_DATASOURCE_USERNAME: UzEzUDMxQTIwOQ==
  # SPRING_DATASOURCE_PASSWORD: tickget209
  SPRING_DATASOURCE_PASSWORD: dGlja2dldDIwOQ==
  # SPRING_REDIS_PASSWORD: (empty string)
  SPRING_REDIS_PASSWORD: ""
  # MINIO_ACCESS_KEY: miniorootadmin
  MINIO_ACCESS_KEY: bWluaW9yb290YWRtaW4=
  # MINIO_SECRET_KEY: miniorootadmin
  MINIO_SECRET_KEY: bWluaW9yb290YWRtaW4=
