apiVersion: v1
kind: Service
metadata:
  name: analyst-server-service
spec:
  selector:
    app: analyst-server
  ports:
    - protocol: TCP
      port: 80        # 서비스가 노출하는 포트
      targetPort: 8000  # 파드의 컨테이너 포트 (uvicorn)
  type: ClusterIP