apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: db
type: Opaque
data:
  # Original: tickget209
  root-user: dGlja2dldDIwOQ==

  # Original: hiiiiky209
  root-password: aGlpaWlreTIwOQ==
