apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-server-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: search-server
  template:
    metadata:
      labels:
        app: search-server
    spec:
      containers:
      - name: search-server
        image: kkaebu/search-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: TZ
          value: "Asia/Seoul"
        envFrom:
          - configMapRef:
              name: search-server-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "1536Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
