apiVersion: v1
kind: Secret
metadata:
  name: test-server-secret
type: Opaque
data:
  # Spring Boot가 읽을 환경 변수 (값은 Base64 인코딩됨)
  
  # SPRING_DATASOURCE_USERNAME: S13P31A209
  SPRING_DATASOURCE_USERNAME: UzEzUDMxQTIwOQ==
  
  # SPRING_DATASOURCE_PASSWORD: tickget209
  SPRING_DATASOURCE_PASSWORD: dGlja2dldDIwOQ==
  
  # SPRING_DATA_MONGODB_URI: mongodb+srv://S13P31A209:tickget209@...
  SPRING_DATA_MONGODB_URI: bW9uZ29kYitzcnY6Ly9TMTNQMzFBMjA5OnRpY2tnZXQyMDlAc3NhZnkubmdpdmwubW9uZ29kYi5uZXQvUzEzUDMxQTIwOT9hdXRoU291cmNlPWFkbWlu