apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - middleware.yaml
  - ingress-route.yaml

namespace: prod

images:
- name: kkaebu/user-server
  newTag: prod-latest
