apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # !!! 중요: 이메일 주소를 실제 사용하시는 주소로 변경하세요. !!!
    email: h2sorginal@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: traefik # 사용 중인 Ingress Class 이름
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # !!! 중요: 이메일 주소를 실제 사용하시는 주소로 변경하세요. !!!
    email: h2sorginal@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: traefik # 사용 중인 Ingress Class 이름