apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: db
spec:
  selector:
    app: mongodb
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: db
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
