apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: db
data:
  mongod.conf: |
    # MongoDB Configuration File

    # Network interfaces
    net:
      port: 27017
      bindIp: 0.0.0.0

    # Storage
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: 0.5  # 512MB cache

    # System Log
    systemLog:
      destination: file
      path: /data/db/mongod.log
      logAppend: true

    # Process Management
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo

    # Security (authentication enabled)
    security:
      authorization: enabled
