apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: db
type: Opaque
stringData:
  # IMPORTANT: Change these values in production!
  username: "tickget"
  password: "hiiiiky"

  # Connection string for applications
  connection-string: "mongodb://tickget:hiiiiky@mongodb:27017/ticketing_db?authSource=admin"
