apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: db
type: Opaque
data:
  # Original: tickget
  username: dGlja2dldA==

  # Original: hiiiiky
  password: aGlpaWlreQ==

  # Original: mongodb://tickget:hiiiiky@mongodb:27017/ticketing_db?authSource=admin
  connection-string: bW9uZ29kYjovL3RpY2tnZXQ6aGlpaWlreUBtb25nb2RiOjI3MDE3L3RpY2tldGluZ19kYj9hdXRoU291cmNlPWFkbWlu
