apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
type: Opaque
data:
  # Original: hiiiiky
  root-password: aGlpaWlreQ==

  # Original: tickget
  username: dGlja2dldA==

  # Original: hiiiiky
  password: aGlpaWlreQ==

  # Original: mysql://tickget:hiiiiky@mysql:3306/tickget_db
  connection-string: bXlzcWw6Ly90aWNrZ2V0OmhpaWlpa3lAbXlzcWw6MzMwNi90aWNrZ2V0X2Ri
