# apps/frontend/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 사용할 base
resources:
- ../../base
- configmap.yaml

# 2. dev 네임스페이스 적용
namespace: dev

# 3. 이미지 태그 설정
images:
- name: kkaebu/tickget-frontend
  newTag: dev-417ab15e

# 4. replicas 설정
patches:
- path: patch-replicas.yaml
  target:
    kind: Deployment
    name: frontend-deployment
