apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redis-commander-ingress
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`redis.tickget.kr`)
      kind: Rule
      services:
        - name: redis-commander-service
          port: 80
          namespace: monitoring
  # TLS 설정 (redis.tickget.kr 인증서 사용)
  tls:
    secretName: redis-tickget-kr-tls
